### PR TITLE
Make parser parse full.txt

### PR DESCRIPTION
**Pull request by Lysxia**
After parsing comments (after `immediateDocComment` in `artifactDecl`), nstead of failing if there is no artifact, return `Nothing`.

### CODE REVIEW

**Comment by Lysxia** [comment]
ping @complyue in case you didn't see this

**Comment by complyue** [comment]
Update:
I just realized this is a PR and you've made `untilNothing` to replace `manyTill`, extra thanks for your effort!

@Lysxia Thanks! 

But then I feel I'll need a customized `manyTill` as in https://github.com/complyue/dcp/blob/91616496e43d153ca8ae92c0d030b3cdc351fb6c/src/Parser.hs#L136 and as the actual AST is rather more complex than this minimal example, other standard combinators tend to need customization, I'd think that'll go too costly ergonomic wise.

**Comment by complyue** [comment]
@Lysxia FYI, I come to better understanding of the issue, and seems it can also be addressed like https://github.com/complyue/dcp/commit/f0c12d51e30cfc49e9e580e5e766c4e8f7d4b54e or https://github.com/complyue/dcp/commit/2600179ab480b2778589495c1ab0bb092f3ae7df , very similar to your solution.

But I'm still wondering, this really unaddressable from the combinator lib's design space? Why?

**Comment by Lysxia** [comment]
> But I'm still wondering, this really unaddressable from the combinator lib's design space? Why?

Isn't `manyTill` (defined in this PR) such a combinator? Note that its type can be generalized:

```
manyTill :: Monad m => m (Maybe a) -> m [a]
```

This is also called `unfoldM` in the library monad-loops https://hackage.haskell.org/package/monad-loops-0.4.3/docs/Control-Monad-Loops.html

If `manyTill` doesn't answer your question, then I don't understand what you're looking for. "the combinator lib's design space" sounds like an artificial separation of domains to me.

> other standard combinators tend to need customization, I'd think that'll go too costly ergonomic wise.

There are too many combinators one could imagine. It is impractical to list them all in a library, because people are just going to forget about them. Rather than "customizing standard combinators", I see this as merely "defining the combinators you need". Being able to define the combinators you need is a core aspect of functional programming, so I question the claim that doing so is "too costly ergonomic wise".

**Comment by complyue** [comment]
@Lysxia 

I assume you mean `untilNothing` as implemented in this PR by `manyTill` in your reply above.

By "the combinator lib's design space" I mean some mechanism around `ParsecT` instead of the `a` as in the final type `Parser a`. IMHO, it will definitely be more ergonomic without affording extra transforming around `a`, so long as `ParsecT` can solely give a solution. I get to realize that transforming around `a` is reasonable, but still not clear why we can not get rid of it.

Update: So maybe "the combinator engine's design space" is more accurate to express my intent.

**Comment by Lysxia** [comment]
> I assume you mean untilNothing as implemented in this PR by manyTill in your reply above.

Oops, sorry. That's indeed what I meant.

**Comment by complyue** [comment]
@Lysxia FYI, I'd like to close this PR now.

With help from Olaf, I think I just cracked my confusion now, that I failed
to distinguish between the 2 monoid structures of concatenation and
choice, and have wrongly assumed somehow Alternative can do
concatenation at the same time as choice making.

Now I understand it clearly that parsers can be concatenated only if
their result type is concatenatable, so if the combinator lib is to
address my demand, it can define `maynTill'` with the parser type
fixed like:

```hs
manyTill' :: Monoid a => Parser a -> Parser end -> Parser a
manyTill' p end = go where go = (mempty <$ end) <|> liftA2 mappend p go
```

Then I can tune my result types, and implement my parsers like:

```hs
type ArtDecl = (Maybe DocComment, Text)
data ModuleDecl m = (Applicative m, Monoid (m ArtDecl)) =>
  ModuleDecl (Maybe DocComment) (m ArtDecl)

moduleDecl :: (Applicative m, Monoid (m ArtDecl)) => Parser (ModuleDecl m)
moduleDecl = lexeme $ do
  sc
  moduCmt <- optional docComment
  arts    <- manyTill' (scWithSemiColons >> artifactDecl) eof
  return $ ModuleDecl moduCmt arts

artifactDecl :: (Applicative m, Monoid (m ArtDecl)) => Parser (m ArtDecl)
artifactDecl = lexeme $ do
  artCmt <- optional immediateDocComment
  choice
    [ eof >> return mempty
    , do
      artBody <- takeWhileP (Just "artifact body")
                            (not . flip elem (";{" :: [Char]))
      return $ pure (artCmt, artBody)
    ]
```

https://github.com/complyue/dcp/blob/39039e62db5f63e61814383ffc2c5f4fba240806/src/Parser.hs#L128-L152

This approach clears my doubts, though doesn't seem more ergonomic compared to approaches like

  https://github.com/complyue/dcp/commit/2600179ab480b2778589495c1ab0bb092f3ae7df

or 

  https://github.com/complyue/dcp/commit/f0c12d51e30cfc49e9e580e5e766c4e8f7d4b54e

Well, then I know my options now.

**Pull request closed without merging**
